### ISSUE TITLE
Missing ckpts

### ISSUE THREAD

**Issue by abcdvzz** [CityU-LANTERN/GRASP_retro#1]
Hi, I notice some ckpts missing in your code, e.g., rmt.pt, fmt.pt, mt.retro.vacab.src, and materials.txt. Thanks.

**Comment by yuyemin** [comment]
Hi, sorry for the late reply. Please download the checkpoint and resource folder using this link[https://www.dropbox.com/scl/fi/im7arliard8z1mivc60h9/model_ckpt.tar.gz?rlkey=qz7r9xonhv162eljtxjuotenj&dl=0](url). Thanks!

**Comment by JunSeok94** [comment]
Hi, I have the same problem and the link is expired. Could you receive another link please?

**Comment by JunSeok94** [comment]
oh, the link worked well! Thanks a lot
